<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyName>日期提醒</AssemblyName>
    <StartupObject>DateReminder.Program</StartupObject>
    <LangVersion>latest</LangVersion>
    <Version>1.5.0</Version>
    <FileVersion>1.5.0</FileVersion>
    <AssemblyVersion>1.5.0</AssemblyVersion>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>true</GenerateTargetFrameworkAttribute>
    <OutputPath>bin\Release\net48\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.0" />
    <Reference Include="System.Management" />
  </ItemGroup>

</Project>
